apiVersion: v1
kind: Service
metadata:
  name: upwind-web-app-service
spec:
  selector:
    app: upwind-web-app  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8080  
  type: LoadBalancer
